version: '3.5'

services:
  quake3dc:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000" # <- Change this to your UID:GID
    restart: always
    ports: 
      - 27960:27960
      - 27960:27960/udp
    volumes:
      - ./config/baseq3:/server/q3a/baseq3
      - ./.q3a://.q3a
    command: 
      - +set net_port 27960 +exec "presets/ffa.cfg" +map dc_map02 +set sv_hostname "Q3A DC - FFA SERVER" +set fraglimit 30 +set timelimit 10
    security_opt:
      - no-new-privileges:true